{% set name = "cufflinks-py" %}
{% set version = "0.17.0" %}
{% set sha256 = "a30724ff73fa83c80c29c701b0d6426aea562d8aed97f49d3cc9c209eadb8ac7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/cufflinks/cufflinks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - plotly >=2.0.0,<3.0.0
  run:
    - python
    - six 
    - pandas 
    - plotly >=2.0.0,<3.0.0
    - colorlover >=0.2
    - ipython

test:
  imports:
    - cufflinks

about:
  home: https://github.com/santosjorge/cufflinks
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Productivity Tools for Plotly + Pandas'
  description: 
    This library binds the power of plotly with the flexibility of pandas for easy plotting.
  doc_url: https://plot.ly/ipython-notebooks/cufflinks/
  dev_url: https://github.com/santosjorge/cufflinks

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
